version: '3'
services:
  api:
    image: aurelianosza/express
    volumes:
      - ./service/:/usr/src/app
    ports:
      - 8080:8080
    networks:
      - persistence
    restart: always
  mongo:
    image: mongo:latest
    volumes:
      - ./database/:/etc/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD:   
    networks:
      - persistence

networks:
  persistence:
    driver:
      bridge